Repository magnetis/astro-galaxy, pull requests merged in 2019-12, with the labels that each got.

#22 Add accessibility_issue.md
  .github/ISSUE_TEMPLATE/accessibility_issue.md
Labels: a11y

#23 Update icons accordingly to astro spec
  packages/icons/index.story.js
  packages/icons/svg-icons/icon-bank.svg
  packages/icons/svg-icons/icon-calendar-check.svg
  packages/icons/svg-icons/icon-chart.svg
  packages/icons/svg-icons/icon-close.svg
  packages/icons/svg-icons/icon-diagonal-left.svg
  packages/icons/svg-icons/icon-diagonal-right.svg
  packages/icons/svg-icons/icon-document.svg
  packages/icons/svg-icons/icon-down.svg
  packages/icons/svg-icons/icon-gift.svg
  packages/icons/svg-icons/icon-heart.svg
  packages/icons/svg-icons/icon-invite.svg
  packages/icons/svg-icons/icon-money-bag.svg
  packages/icons/svg-icons/icon-mountain.svg
  packages/icons/svg-icons/icon-page.svg
  packages/icons/svg-icons/icon-return.svg
  packages/icons/svg-icons/icon-sheet.svg
  packages/icons/svg-icons/icon-tax.svg
  packages/icons/svg-icons/icon-time.svg
  packages/icons/svg-icons/icon-transactions.svg
  packages/icons/svg-icons/icon-update.svg
  packages/icons/svg-icons/icon-upload.svg
Labels: astro-galaxy-icons

#26 [23890] Add typography components
  packages/components/src/Heading/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Heading/__tests__/index.test.js
  packages/components/src/Heading/index.js
  packages/components/src/Heading/index.story.js
  packages/components/src/Text/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Text/__tests__/index.test.js
  packages/components/src/Text/index.js
  packages/components/src/Text/index.story.js
  packages/components/src/index.js
  packages/core/src/theme-provider/index.js
  packages/core/src/themes/control.js
Labels: astro-galaxy-components

#27 Implement layout from current Astro docs
  package.json
  packages/docs/favicon.png
  packages/docs/gatsby-browser.js
  packages/docs/gatsby-config.js
  packages/docs/gatsby-node.js
  packages/docs/gatsby-ssr.js
  packages/docs/package.json
  packages/docs/src/components/Layout.js
  packages/docs/src/components/Menu.js
  packages/docs/src/components/Sidebar.js
  packages/docs/src/components/astro-logo.svg
  packages/docs/src/components/layout.js
  packages/docs/src/utils/breakpoints.js
  yarn.lock
Labels: documentation

#28 Introduce IconButton, IconOutlineButton and IconGhostButton
  .storybook/webpack.config.js
  packages/components/src/IconButton/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/IconButton/__tests__/index.test.js
  packages/components/src/IconButton/index.js
  packages/components/src/IconButton/index.story.js
  packages/components/src/IconGhostButton/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/IconGhostButton/__tests__/index.test.js
  packages/components/src/IconGhostButton/index.js
  packages/components/src/IconGhostButton/index.story.js
  packages/components/src/IconOutlineButton/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/IconOutlineButton/__tests__/index.test.js
  packages/components/src/IconOutlineButton/index.js
  packages/components/src/IconOutlineButton/index.story.js
  packages/core/src/themes/control.js
Labels: astro-galaxy-components

#29 Create the Playground component to make the examples interactive
  packages/docs/package.json
  packages/docs/src/components/Playground.js
  packages/docs/src/pages/index.mdx
  yarn.lock
Labels: documentation

#33 [Docs] - Buttons page
  packages/components/src/index.js
  packages/docs/src/pages/buttons.mdx
Labels: documentation

#35 [Docs] - Remove unused Icon import
  packages/docs/src/components/Menu.js
Labels: documentation

#36 Typography page
  packages/docs/src/components/Layout.js
  packages/docs/src/components/Menu.js
  packages/docs/src/components/Sidebar.js
  packages/docs/src/pages/typography.mdx
Labels: documentation

#38 Improve buttons doc page, adding props table and more
  packages/docs/src/components/Layout.js
  packages/docs/src/components/Playground.js
  packages/docs/src/components/PropsTable.js
  packages/docs/src/pages/buttons.mdx
Labels: documentation

#45 Introduce checkbox
  packages/components/src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Checkbox/__tests__/index.test.js
  packages/components/src/Checkbox/index.js
  packages/components/src/Checkbox/index.story.js
  packages/components/src/Label/index.js
  packages/components/src/index.js
  packages/docs/src/pages/buttons.mdx
  packages/docs/src/pages/controls-toggles.mdx
Labels: astro-galaxy-components, documentation

#48 Add support for reduce motion
  packages/core/src/theme-provider/index.js
Labels: astro-galaxy-core
