Repository magnetis/astro-galaxy, pull requests merged in 2020-04, with the labels that each got.

#69 Release 1.0.0 alpha.4
  CHANGELOG.md
  packages/components/package.json
  packages/core/package.json
  packages/docs/package.json
  packages/icons/package.json
  packages/tokens/package.json
Labels: release

#71 Add inputs page on the Storybook docs
  docs/06_Inputs.stories.mdx
  docs/components/PreviewGrid.js
  docs/components/index.js
  packages/components/src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Tab/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/index.js
Labels: documentation

#72 Add icons page
  .storybook/webpack.config.js
  docs/04_Iconography.stories.mdx
  docs/components/IconsCollection.js
Labels: documentation

#74 Add colors and gradients page
  docs/02_Colors.stories.mdx
  docs/components/ColorsCollection.js
Labels: documentation

#73 Add docs home
  .storybook/preview-head.html
  .storybook/webpack.config.js
  docs/01_Home.stories.mdx
  docs/06_Inputs.stories.mdx
  docs/assets/illustrations/accessible.png
  docs/assets/illustrations/atomic.png
  docs/assets/illustrations/open.png
  docs/components/Card.js
  docs/components/GitHubButtons.js
  docs/components/PreviewGrid.js
  docs/components/SectionTitle.js
  docs/components/index.js
  packages/components/src/Button/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Button/index.js
  packages/components/src/IconButton/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/IconGhostButton/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/IconOutlineButton/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/InputControl/__tests__/__snapshots__/index.test.js.snap
Labels: documentation

#75 Part of the journey is the end - Remove @magnetis/astro-galaxy-docs
  README.md
  package.json
  packages/components/src/Button/index.story.js
  packages/components/src/Checkbox/index.story.js
  packages/components/src/Heading/index.story.js
  packages/components/src/IconButton/index.story.js
  packages/components/src/IconGhostButton/index.story.js
  packages/components/src/IconLinkButton/index.story.js
  packages/components/src/IconOutlineButton/index.story.js
  packages/components/src/InputControl/index.story.js
  packages/components/src/InputFilePreview/index.story.js
  packages/components/src/InputGhost/index.story.js
  packages/components/src/InputMasked/index.story.js
  packages/components/src/InputText/index.story.js
  packages/components/src/Label/index.story.js
  packages/components/src/Link/index.story.js
  packages/components/src/OutlineButton/index.story.js
  packages/components/src/Radio/index.story.js
  packages/components/src/Slider/index.story.js
  packages/components/src/Tab/index.story.js
  packages/components/src/Tabbed/index.story.js
  packages/components/src/Table/index.story.js
  packages/components/src/Text/index.story.js
  packages/components/src/TextArea/index.story.js
  packages/components/src/Toggle/index.story.js
  packages/docs/favicon.png
  packages/docs/gatsby-config.js
  packages/docs/gatsby-node.js
  packages/docs/package.json
  packages/docs/src/components/IconsCollection.js
  packages/docs/src/components/Layout.js
  packages/docs/src/components/Menu.js
  packages/docs/src/components/Playground.js
  packages/docs/src/components/PropsTable.js
  packages/docs/src/components/Sidebar.js
  packages/docs/src/components/astro-logo.svg
  packages/docs/src/pages/404.mdx
  packages/docs/src/pages/buttons.mdx
  packages/docs/src/pages/controls-toggles.mdx
  packages/docs/src/pages/iconography.mdx
  packages/docs/src/pages/index.mdx
  packages/docs/src/pages/inputs.mdx
  packages/docs/src/pages/typography.mdx
  packages/docs/src/utils/breakpoints.js
  packages/docs/yarn.lock
  packages/icons/index.story.js
  plop-templates/component/index.story.js.hbs
Labels: documentation

#76 Configure new docs deploy
  .gitignore
  docs/.storybook/main.js
  docs/.storybook/manager-head.html
  docs/.storybook/manager.js
  docs/.storybook/preview-head.html
  docs/.storybook/preview.js
  docs/.storybook/theme.js
  docs/.storybook/webpack.config.js
  docs/src/01_Home.stories.mdx
  docs/src/02_Colors.stories.mdx
  docs/src/03_Typography.stories.mdx
  docs/src/04_Iconography.stories.mdx
  docs/src/05_Buttons.stories.mdx
  docs/src/06_Inputs.stories.mdx
  docs/src/07_ControlsAndToggles.stories.mdx
  docs/src/08_Tables.stories.mdx
  docs/src/components/Card.js
  docs/src/components/ColorsCollection.js
  docs/src/components/GitHubButtons.js
  docs/src/components/IconsCollection.js
  docs/src/components/PreviewDivider.js
  docs/src/components/PreviewGrid.js
  docs/src/components/SectionTitle.js
  docs/src/components/index.js
  package.json
  yarn.lock
Labels: documentation

#80 Improve storybook loading time
  docs/.storybook/main.js
  docs/.storybook/manager-head.html
  docs/.storybook/preview-head.html
  docs/src/08_Tables.stories.mdx
  docs/src/components/GitHubButtons.js
  package.json
  packages/components/src/index.js
  yarn.lock
Labels: documentation

#81 Add favicon to docs website
  docs/.storybook/manager-head.html
  docs/assets/favicon.png
  package.json
Labels: documentation

#83 Add doc on how to release new versions
  RELEASES.md
Labels: documentation

#85 Release 1.0.0-alpha.5
  CHANGELOG.md
  packages/components/package.json
  packages/core/package.json
  packages/icons/package.json
  packages/themes/package.json
  packages/tokens/package.json
Labels: astro-galaxy-themes, release
