Repository magnetis/astro-galaxy, pull requests merged in 2020-05, with the labels that each got.

#86 Fix Tabbed icons and doc icons
  docs/src/components/IconsCollection.js
  packages/components/src/Tabbed/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Tabbed/index.js
Labels: astro-galaxy-components, documentation, enhancement

#89 Release 1.0.0
  CHANGELOG.md
  packages/components/package.json
  packages/icons/package.json
  packages/themes/package.json
  packages/tokens/package.json
Labels: release

#90 Add galaxy-tokens dependency to galaxy-themes
  packages/themes/package.json
Labels: astro-galaxy-themes

#92 Add rollup build to tokens package
  package.json
  packages/tokens/package.json
  packages/tokens/rollup.config.js
Labels: astro-galaxy-tokens

#93 Release 1.0.2
  CHANGELOG.md
  packages/components/package.json
  packages/icons/package.json
  packages/themes/package.json
  packages/tokens/package.json
Labels: release

#95 Add new icons
  docs/src/components/IconsCollection.js
  packages/icons/svg-icons/icon-airplane.svg
  packages/icons/svg-icons/icon-car.svg
  packages/icons/svg-icons/icon-education.svg
Labels: astro-galaxy-icons

#96 Release 1.1.0
  CHANGELOG.md
  packages/components/package.json
  packages/icons/package.json
  packages/themes/package.json
  packages/tokens/package.json
Labels: release

#97 Adds miscellaneous fixes
  docs/src/03_Typography.stories.mdx
  docs/src/07_ControlsAndToggles.stories.mdx
  docs/src/components/Card.js
  packages/components/src/InputMasked/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Tab/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Tab/__tests__/index.test.js
  packages/components/src/Tabbed/__tests__/index.test.js
  packages/components/src/Text/__tests__/__snapshots__/index.test.js.snap
  packages/components/src/Text/__tests__/index.test.js
  packages/components/src/Text/index.js
  packages/components/src/index.js
  packages/themes/src/web/index.js
Labels: bug

#98 Release 1.1.1
  CHANGELOG.md
  packages/components/package.json
  packages/icons/package.json
  packages/themes/package.json
  packages/tokens/package.json
Labels: release
